/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IRandomTable, IRandomTableInterface } from "../IRandomTable";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "getRandomTable",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IRandomTable__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomTableInterface {
    return new utils.Interface(_abi) as IRandomTableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRandomTable {
    return new Contract(address, _abi, signerOrProvider) as IRandomTable;
  }
}
